### ISSUE TITLE
completion list of method name is double

### ISSUE THREAD

**Issue by manaphp** [klesun/deep-assoc-completion#103]
![image](https://user-images.githubusercontent.com/16060165/60763080-8b5ec980-a09f-11e9-9b7f-115ff46f9b86.png)

**Comment by klesun** [comment]
Hi. I believe this completion is not from the plugin (no bluish icon). I'll double check when I have a pc in front of me.

**Comment by klesun** [comment]
![image](https://user-images.githubusercontent.com/5202330/60904161-3aa3c800-a27b-11e9-865e-95d5ea8caf17.png)
Does not reproduce out of the box on my side. If this still bothers you, could you check if the issue still happens when you disable the plugin? If the issue *does* only reproduce with the plugin enabled, could you, please, provide a minimal test case?

**Comment by manaphp** [comment]
sorry, i can not reproduce it ,now...

**Comment by klesun** [comment]
ok, I guess I'm closing this issue then.
