### ISSUE TITLE
TypeProvider contract violation

### ISSUE THREAD

**Issue by neuro159** [klesun/deep-assoc-completion#15]
Error while indexing Symfony\Component\DependencyInjection\ExpressionLanguageProvider.php
To reindex this file IDEA has to be restarted

java.lang.RuntimeException: TypeProvider contract violation? by class org.klesun.deep_assoc_completion.entry.AssocTypePvdr on $variables['container']

**Comment by neuro159** [comment]
300+reports and counting
please fix (DM me for help)
or plugin might be banned

**Comment by klesun** [comment]
Thank you for report. I temporarily disabled the feature:
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/40553

I'll reenable it once I fix the issue.

**Comment by klesun** [comment]
Fix: c4cc70551f4b7897126c3c8c6219e52aaaf20b1d

The problem was that Type Provider was called during Project Indexing. It uses functions like `PsiPolyVariantReference::multiResolve` that throw the Contract Violation exception if called during indexing. 

The fix checks whether Indexing is in progress with `DumbService.isDumb()` and does not run the type resolution if it is.
