### ISSUE TITLE
Exception: com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by ktomk** [klesun/deep-assoc-completion#181]
I just had a hard crash (SIGSEV) in Phpstorm EAP and restarted it. When it came back up, it reported the Phpstorm crash and a second report was about that index were borked or something with stubs along the index line.

I suspect this exception is related to the crash. The plugin likely was not part of the crash.

Just reporting in case it is of use. Currently only appeared once. Will restart with index re-validation.

https://gist.github.com/ktomk/712fab7a58daffe88b8bb89363130637

**Comment by klesun** [comment]
Hm, thanks.
If the issue repeats, you can find out the actual plugin that causes the exception in
_File -> Settings -> Languages & Frameworks -> PHP -> deep-assoc-completion_ settings:

![image](https://user-images.githubusercontent.com/5202330/111963833-a506a580-8afc-11eb-80f7-5f6fcf9dbd46.png)

See https://github.com/klesun/deep-assoc-completion/issues/174#issuecomment-782844326

Sorry for the noise in stack trace caused by my plugin.

**Comment by ktomk** [comment]
All fine, made the setting, whenever it happens again. Good to know, understanding 174. Close in the meantime.
