### ISSUE TITLE
End brace and semicolon inserted, but not quote

### ISSUE THREAD

**Issue by chuckadams** [klesun/deep-assoc-completion#187]
In other words, I type `$foo['ba<CTRL-SPACE>` and get completions for 'bar' and 'baz'.  I select bar, hit enter, and get `$foo['bar];`, without the closing quote.  Sometimes it doesn't add the `];` but adds a newline instead.  If I hit tab, it always adds the newline, and in fact after expanding once with tab, hitting enter expands the same way too. 

If I'm already inside a pair of quotes, it behaves with enter, at least until I tab-expand once, at which point it adds a newline after the end quote for both tab and enter.

**Comment by klesun** [comment]
Thanks, was just going to reply to your comment to file this issue =-D
Will take a look. What phpstorm version are you using?

**Comment by klesun** [comment]
Oh, you don't have auto-end-quotes enabled, that pretty much explains everything, never tried using the plugin without it. Will try to post a small fix soon.

**Comment by klesun** [comment]
Yeah, it behaves pretty nasty with "Insert pair quote" disabled ;c

**Comment by chuckadams** [comment]
I'm on IDEA Ultimate 2021.1.3.  But as you can see, it's more about the quotes:  It does misbehave the same way if I have pair quotes enabled and delete the end quote.

**Comment by klesun** [comment]
Released the fix in [2021.07.18.002](https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/versions/stable/128211)

![image](https://user-images.githubusercontent.com/5202330/126054563-052ff10f-d348-42b2-bdeb-85b635681d49.png)


Hopefully now it behaves correctly in every possible case. It should not jump to new line anymore, should automatically close unterminated quote and always be placed after the `]` if `]` is present, otherwise after the closing quote.
