### ISSUE TITLE
Wrong completion for array key

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#27]
Following example code:
```php
<?php
/**
 * @var array $otherOptions = MyModule::options()
 */

$newOptions = [
    'something' => $otherOptions['view_all'],
];

echo $otherOptions['<caret>'];
```

At caret `something` gets listed, but it's not defined for `$otherOptions` array but only in `$newOptions`.

Is that a bug from this plugin or PhpStorm itself?

**Comment by klesun** [comment]
This bug is from PhpStorm itself. You can distinct these (usually incorrect) options by absence of type info and icon and font being thin (completions from the plugin are *bold*).

Built-In completion:
![image](https://user-images.githubusercontent.com/5202330/34742701-f6736c4e-f57e-11e7-82ae-7f832bbc9587.png)

Plugin completion:
![image](https://user-images.githubusercontent.com/5202330/34742835-8d5cff62-f57f-11e7-8646-96f3b44b435c.png)

Sadly, I don't know how to distinct these built-in suggestions from suggestions provided by other plugins, so I can't safely exclude them.

In case you are interested, the interaction with other completion sources happens inside `org.klesun.deep_assoc_completion.completion_providers.DeepKeysPvdr::addCompletions()` by the `result.runRemainingContributors()`. Currently it only removes duplicate completion options.

You can also file a bug report to the phpstorm guys, if you want: 
https://youtrack.jetbrains.com/issues/WI#newissue=25-1835255

**Comment by King2500** [comment]
Reported: https://youtrack.jetbrains.com/issue/WI-39506
