### ISSUE TITLE
Weird numeric array keys completion

### ISSUE THREAD

**Issue by King2500** [klesun/deep-assoc-completion#29]
Sometimes i get weird numeric completion list when inside a string litery key:

```php
$arr['<caret>']
```
2
1
0 
and so on

**Comment by klesun** [comment]
You probably are talking about something like this?
![image](https://user-images.githubusercontent.com/5202330/35178553-7a34c282-fd93-11e7-92d1-345bd2af1786.png)

I show numbers from `0` to `4` to show that this is array of values whose keys were not set explicitly. Often that means that this array is _list_ you would usually fill using `$arr[] = ...` or `$arr[$i] = ...`. But if your case is similar to my screenshot above, I can understand your confusion.

I don't want to show _nothing_ in completion options, since it would make _list_ arrays undistinguishable from something that does not have keys (like string or object).  But I can, at least, make this behaviour a bit smarter...

I'll make it suggest the `0-4` completion only when I know for sure that array keys are numbers. I'll also try to find out possible string values of the variable if you set key with a variable (`$arr[$i] = ...`). I'll also show something less confusing when key names are unknown, like empty string, instead of `0-4`.

**Comment by King2500** [comment]
I understand.

But when you select the suggested entry you'll get something like `$arr['0']`. Which is definitely not the same as `$arr[0]` and not wanted.
Maybe it's possible to replace the `'`. Have a look and try to implement an `InsertHandler` for your `LookupElement`s. So it "completes" to `$arr[0]`.

**Comment by klesun** [comment]
Yes, I can try this too. I agree that it would make more sense, even though it will be harder to implement. I'll look into the `InsertHandler`.

But just for info, from the viewpoint of PHP `$arr['0']` and `$arr[0]` are doing same thing. since PHP implicitly converts and stores every integer numeric string key as integer:
```php
php > $arr = ['0' => 3, 2 => 4, '-1' => 5, '5.6' => 6];
php > var_export($arr);
array (
  0 => 3,
  2 => 4,
  -1 => 5,
  '5.6' => 6,
)
php > var_export(array_map('gettype', array_keys($arr)));
array (
  0 => 'integer',
  1 => 'integer',
  2 => 'integer',
  3 => 'string',
)
php > print($arr[0]);
3
php > print($arr['0']);
3
```

**Comment by klesun** [comment]
Fixed. 
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion/update/42701
