### ISSUE TITLE
Please document plugin options

### ISSUE THREAD

**Issue by hailwood** [klesun/deep-assoc-completion#58]
Hey @klesun,

Any chance you could document what the various settings do under Languages & Frameworks > PHP > deep-assoc-completion?
![image](https://user-images.githubusercontent.com/709773/49835841-5b9b5c00-fe05-11e8-858a-1db55cd52763.png)

**Comment by klesun** [comment]
I guess I will... They exist more for debuging purposes though, since default values are _supposedly_ optimal for any project. And half of them aren't doing anything anymore. And there is a type hint which appears when you hover on a setting label...

In short:
- First three settings can be ignored, `Background Deep Type Provider` relates to the disabled by default mechanism that tells IDEA what type variable has using my plugin (so that methods were not marked with red in complex context). It is disabled because this caused major performance issues in projects with frameworks like Laravel https://github.com/klesun/deep-assoc-completion/issues/33.
- _Explicit user action completion depth limit_ defines how long expression chain may get when you hit _Ctrl + Space_.
- _Auto-popup completion depth limit_ same, but applies to type resolution that happens on it's own when you just type `[]` or `''` and get auto-completion.
- _Total expression limit_ is a safeguard against circular references for cases when plugin looses control over situation. It counts _all_ expressions that appeared in resolution unlike the depth limit which counted only related expressions.
- _Remove unused use-s on save_ is a small feature I added for my needs. Like label says, it removes greyed `use SomeNs\SomeCls.php`-s from the file when you hit _Ctrl + S_ (or switch window probably). If I'm not mistaken there was some similar functionality in phpstorm itself, but it sorted all `use`-s alphabetically causing a lot of diff.

So, the summary is: if you have very complex structures (like 10 nested arrays) in your code and you think plugin should be able to process that, you can try setting _Explicit user action completion depth limit_ higher. If you experience noticable delays when you type array keys or strings passed to a function, you may lower the _Auto-popup completion depth limit_ (if this is the case, you can let me know, I'll lower the default value, btw).

**Comment by hailwood** [comment]
Thanks @klesun,
I'm just a curious sole was was wondering what they were, no problems with the plugin!
Also, thanks for the tip regarding the tooltips, had no idea they were there!
